# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

CC=/usr/bin/gcc
AS=/usr/bin/gcc
CXX=/usr/bin/gcc
MXX=/usr/bin/gcc
MM=/usr/bin/gcc

AR=/usr/bin/ar
LD=/usr/bin/g++
SH=/usr/bin/g++

file_receiver_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
file_receiver_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
file_receiver_LDFLAGS=-m64 -Llib/linux -Llib/linux/release -s -luds_base -lpthread
uds_base_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
uds_base_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
uds_base_ARFLAGS=-cr
file_sender_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
file_sender_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
file_sender_LDFLAGS=-m64 -Llib/linux -Llib/linux/release -s -luds_base -lpthread
echo_client_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
echo_client_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
echo_client_LDFLAGS=-m64 -Llib/linux -Llib/linux/release -s -luds_base -lpthread
simple_client_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
simple_client_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
simple_client_LDFLAGS=-m64 -Llib/linux -Llib/linux/release -s -luds_base -lpthread -luds_json -ljsoncpp
uds_base_cli_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
uds_base_cli_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
uds_base_cli_LDFLAGS=-m64 -Llib/linux -Llib/linux/release -s -luds_base -lpthread
benchmark_server_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
benchmark_server_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
benchmark_server_LDFLAGS=-m64 -Llib/linux -Llib/linux/release -s -luds_base -lpthread
uds_json_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
uds_json_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
uds_json_ARFLAGS=-cr
uds_json_cli_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
uds_json_cli_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
uds_json_cli_LDFLAGS=-m64 -Llib/linux -Llib/linux/release -s -luds_base -lpthread -luds_json -ljsoncpp
simple_server_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
simple_server_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
simple_server_LDFLAGS=-m64 -Llib/linux -Llib/linux/release -s -luds_base -lpthread -luds_json -ljsoncpp
echo_server_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
echo_server_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
echo_server_LDFLAGS=-m64 -Llib/linux -Llib/linux/release -s -luds_base -lpthread
benchmark_client_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
benchmark_client_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++17 -Isrc -Ithird_party -Wreturn-type -Wsign-compare -Wunused-variable -Wswitch -Werror -Wno-unused-result -Wno-deprecated-declarations -Wno-unused-parameter -DNDEBUG
benchmark_client_LDFLAGS=-m64 -Llib/linux -Llib/linux/release -s -luds_base -lpthread

default:  file_receiver uds_base file_sender echo_client simple_client uds_base_cli benchmark_server uds_json uds_json_cli simple_server echo_server benchmark_client

all:  file_receiver uds_base file_sender echo_client simple_client uds_base_cli benchmark_server uds_json uds_json_cli simple_server echo_server benchmark_client

.PHONY: default all  file_receiver uds_base file_sender echo_client simple_client uds_base_cli benchmark_server uds_json uds_json_cli simple_server echo_server benchmark_client

file_receiver: bin/file_receiver
bin/file_receiver: lib/linux/release/libuds_base.a build/obj/file_receiver/linux/x86_64/release/example/file_transfer/receiver.cpp.o
	@echo linking.release file_receiver
	@mkdir -p bin
	@$(LD) -o bin/file_receiver build/obj/file_receiver/linux/x86_64/release/example/file_transfer/receiver.cpp.o $(file_receiver_LDFLAGS) > build/.build.log 2>&1

build/obj/file_receiver/linux/x86_64/release/example/file_transfer/receiver.cpp.o: example/file_transfer/receiver.cpp
	@echo compiling.release example/file_transfer/receiver.cpp
	@mkdir -p build/obj/file_receiver/linux/x86_64/release/example/file_transfer
	@$(CXX) -c $(file_receiver_CXXFLAGS) -o build/obj/file_receiver/linux/x86_64/release/example/file_transfer/receiver.cpp.o example/file_transfer/receiver.cpp > build/.build.log 2>&1

uds_base: lib/linux/release/libuds_base.a
lib/linux/release/libuds_base.a: build/obj/uds_base/linux/x86_64/release/src/uds/base/base_client.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/base_server.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/impl_base_client.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/uds_packet.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/impl_base_server.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/util/uds_util.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/thread/static_thread_pool.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/error_code.cpp.o
	@echo linking.release libuds_base.a
	@mkdir -p lib/linux/release
	@$(AR) $(uds_base_ARFLAGS) lib/linux/release/libuds_base.a build/obj/uds_base/linux/x86_64/release/src/uds/base/base_client.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/base_server.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/impl_base_client.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/uds_packet.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/impl_base_server.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/util/uds_util.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/thread/static_thread_pool.cpp.o build/obj/uds_base/linux/x86_64/release/src/uds/base/error_code.cpp.o > build/.build.log 2>&1

build/obj/uds_base/linux/x86_64/release/src/uds/base/base_client.cpp.o: src/uds/base/base_client.cpp
	@echo compiling.release src/uds/base/base_client.cpp
	@mkdir -p build/obj/uds_base/linux/x86_64/release/src/uds/base
	@$(CXX) -c $(uds_base_CXXFLAGS) -o build/obj/uds_base/linux/x86_64/release/src/uds/base/base_client.cpp.o src/uds/base/base_client.cpp > build/.build.log 2>&1

build/obj/uds_base/linux/x86_64/release/src/uds/base/base_server.cpp.o: src/uds/base/base_server.cpp
	@echo compiling.release src/uds/base/base_server.cpp
	@mkdir -p build/obj/uds_base/linux/x86_64/release/src/uds/base
	@$(CXX) -c $(uds_base_CXXFLAGS) -o build/obj/uds_base/linux/x86_64/release/src/uds/base/base_server.cpp.o src/uds/base/base_server.cpp > build/.build.log 2>&1

build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/impl_base_client.cpp.o: src/uds/base/impl/impl_base_client.cpp
	@echo compiling.release src/uds/base/impl/impl_base_client.cpp
	@mkdir -p build/obj/uds_base/linux/x86_64/release/src/uds/base/impl
	@$(CXX) -c $(uds_base_CXXFLAGS) -o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/impl_base_client.cpp.o src/uds/base/impl/impl_base_client.cpp > build/.build.log 2>&1

build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/uds_packet.cpp.o: src/uds/base/impl/uds_packet.cpp
	@echo compiling.release src/uds/base/impl/uds_packet.cpp
	@mkdir -p build/obj/uds_base/linux/x86_64/release/src/uds/base/impl
	@$(CXX) -c $(uds_base_CXXFLAGS) -o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/uds_packet.cpp.o src/uds/base/impl/uds_packet.cpp > build/.build.log 2>&1

build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/impl_base_server.cpp.o: src/uds/base/impl/impl_base_server.cpp
	@echo compiling.release src/uds/base/impl/impl_base_server.cpp
	@mkdir -p build/obj/uds_base/linux/x86_64/release/src/uds/base/impl
	@$(CXX) -c $(uds_base_CXXFLAGS) -o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/impl_base_server.cpp.o src/uds/base/impl/impl_base_server.cpp > build/.build.log 2>&1

build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/util/uds_util.cpp.o: src/uds/base/impl/util/uds_util.cpp
	@echo compiling.release src/uds/base/impl/util/uds_util.cpp
	@mkdir -p build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/util
	@$(CXX) -c $(uds_base_CXXFLAGS) -o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/util/uds_util.cpp.o src/uds/base/impl/util/uds_util.cpp > build/.build.log 2>&1

build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/thread/static_thread_pool.cpp.o: src/uds/base/impl/thread/static_thread_pool.cpp
	@echo compiling.release src/uds/base/impl/thread/static_thread_pool.cpp
	@mkdir -p build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/thread
	@$(CXX) -c $(uds_base_CXXFLAGS) -o build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/thread/static_thread_pool.cpp.o src/uds/base/impl/thread/static_thread_pool.cpp > build/.build.log 2>&1

build/obj/uds_base/linux/x86_64/release/src/uds/base/error_code.cpp.o: src/uds/base/error_code.cpp
	@echo compiling.release src/uds/base/error_code.cpp
	@mkdir -p build/obj/uds_base/linux/x86_64/release/src/uds/base
	@$(CXX) -c $(uds_base_CXXFLAGS) -o build/obj/uds_base/linux/x86_64/release/src/uds/base/error_code.cpp.o src/uds/base/error_code.cpp > build/.build.log 2>&1

file_sender: bin/file_sender
bin/file_sender: lib/linux/release/libuds_base.a build/obj/file_sender/linux/x86_64/release/example/file_transfer/sender.cpp.o
	@echo linking.release file_sender
	@mkdir -p bin
	@$(LD) -o bin/file_sender build/obj/file_sender/linux/x86_64/release/example/file_transfer/sender.cpp.o $(file_sender_LDFLAGS) > build/.build.log 2>&1

build/obj/file_sender/linux/x86_64/release/example/file_transfer/sender.cpp.o: example/file_transfer/sender.cpp
	@echo compiling.release example/file_transfer/sender.cpp
	@mkdir -p build/obj/file_sender/linux/x86_64/release/example/file_transfer
	@$(CXX) -c $(file_sender_CXXFLAGS) -o build/obj/file_sender/linux/x86_64/release/example/file_transfer/sender.cpp.o example/file_transfer/sender.cpp > build/.build.log 2>&1

echo_client: bin/echo_client
bin/echo_client: lib/linux/release/libuds_base.a build/obj/echo_client/linux/x86_64/release/example/echo_server/client.cpp.o
	@echo linking.release echo_client
	@mkdir -p bin
	@$(LD) -o bin/echo_client build/obj/echo_client/linux/x86_64/release/example/echo_server/client.cpp.o $(echo_client_LDFLAGS) > build/.build.log 2>&1

build/obj/echo_client/linux/x86_64/release/example/echo_server/client.cpp.o: example/echo_server/client.cpp
	@echo compiling.release example/echo_server/client.cpp
	@mkdir -p build/obj/echo_client/linux/x86_64/release/example/echo_server
	@$(CXX) -c $(echo_client_CXXFLAGS) -o build/obj/echo_client/linux/x86_64/release/example/echo_server/client.cpp.o example/echo_server/client.cpp > build/.build.log 2>&1

simple_client: bin/simple_client
bin/simple_client: lib/linux/release/libuds_json.a lib/linux/release/libuds_base.a build/obj/simple_client/linux/x86_64/release/example/simple_json_server/client.cpp.o
	@echo linking.release simple_client
	@mkdir -p bin
	@$(LD) -o bin/simple_client build/obj/simple_client/linux/x86_64/release/example/simple_json_server/client.cpp.o $(simple_client_LDFLAGS) > build/.build.log 2>&1

build/obj/simple_client/linux/x86_64/release/example/simple_json_server/client.cpp.o: example/simple_json_server/client.cpp
	@echo compiling.release example/simple_json_server/client.cpp
	@mkdir -p build/obj/simple_client/linux/x86_64/release/example/simple_json_server
	@$(CXX) -c $(simple_client_CXXFLAGS) -o build/obj/simple_client/linux/x86_64/release/example/simple_json_server/client.cpp.o example/simple_json_server/client.cpp > build/.build.log 2>&1

uds_base_cli: bin/uds_base_cli
bin/uds_base_cli: lib/linux/release/libuds_base.a build/obj/uds_base_cli/linux/x86_64/release/example/uds_base_cli/uds_base_cli.cpp.o
	@echo linking.release uds_base_cli
	@mkdir -p bin
	@$(LD) -o bin/uds_base_cli build/obj/uds_base_cli/linux/x86_64/release/example/uds_base_cli/uds_base_cli.cpp.o $(uds_base_cli_LDFLAGS) > build/.build.log 2>&1

build/obj/uds_base_cli/linux/x86_64/release/example/uds_base_cli/uds_base_cli.cpp.o: example/uds_base_cli/uds_base_cli.cpp
	@echo compiling.release example/uds_base_cli/uds_base_cli.cpp
	@mkdir -p build/obj/uds_base_cli/linux/x86_64/release/example/uds_base_cli
	@$(CXX) -c $(uds_base_cli_CXXFLAGS) -o build/obj/uds_base_cli/linux/x86_64/release/example/uds_base_cli/uds_base_cli.cpp.o example/uds_base_cli/uds_base_cli.cpp > build/.build.log 2>&1

benchmark_server: bin/benchmark_server
bin/benchmark_server: lib/linux/release/libuds_base.a build/obj/benchmark_server/linux/x86_64/release/example/benchmark/server.cpp.o
	@echo linking.release benchmark_server
	@mkdir -p bin
	@$(LD) -o bin/benchmark_server build/obj/benchmark_server/linux/x86_64/release/example/benchmark/server.cpp.o $(benchmark_server_LDFLAGS) > build/.build.log 2>&1

build/obj/benchmark_server/linux/x86_64/release/example/benchmark/server.cpp.o: example/benchmark/server.cpp
	@echo compiling.release example/benchmark/server.cpp
	@mkdir -p build/obj/benchmark_server/linux/x86_64/release/example/benchmark
	@$(CXX) -c $(benchmark_server_CXXFLAGS) -o build/obj/benchmark_server/linux/x86_64/release/example/benchmark/server.cpp.o example/benchmark/server.cpp > build/.build.log 2>&1

uds_json: lib/linux/release/libuds_json.a
lib/linux/release/libuds_json.a: build/obj/uds_json/linux/x86_64/release/src/uds/json/request.cpp.o build/obj/uds_json/linux/x86_64/release/src/uds/json/client.cpp.o build/obj/uds_json/linux/x86_64/release/src/uds/json/response.cpp.o build/obj/uds_json/linux/x86_64/release/src/uds/json/router.cpp.o build/obj/uds_json/linux/x86_64/release/src/uds/json/message.cpp.o build/obj/uds_json/linux/x86_64/release/src/uds/json/server.cpp.o
	@echo linking.release libuds_json.a
	@mkdir -p lib/linux/release
	@$(AR) $(uds_json_ARFLAGS) lib/linux/release/libuds_json.a build/obj/uds_json/linux/x86_64/release/src/uds/json/request.cpp.o build/obj/uds_json/linux/x86_64/release/src/uds/json/client.cpp.o build/obj/uds_json/linux/x86_64/release/src/uds/json/response.cpp.o build/obj/uds_json/linux/x86_64/release/src/uds/json/router.cpp.o build/obj/uds_json/linux/x86_64/release/src/uds/json/message.cpp.o build/obj/uds_json/linux/x86_64/release/src/uds/json/server.cpp.o > build/.build.log 2>&1

build/obj/uds_json/linux/x86_64/release/src/uds/json/request.cpp.o: src/uds/json/request.cpp
	@echo compiling.release src/uds/json/request.cpp
	@mkdir -p build/obj/uds_json/linux/x86_64/release/src/uds/json
	@$(CXX) -c $(uds_json_CXXFLAGS) -o build/obj/uds_json/linux/x86_64/release/src/uds/json/request.cpp.o src/uds/json/request.cpp > build/.build.log 2>&1

build/obj/uds_json/linux/x86_64/release/src/uds/json/client.cpp.o: src/uds/json/client.cpp
	@echo compiling.release src/uds/json/client.cpp
	@mkdir -p build/obj/uds_json/linux/x86_64/release/src/uds/json
	@$(CXX) -c $(uds_json_CXXFLAGS) -o build/obj/uds_json/linux/x86_64/release/src/uds/json/client.cpp.o src/uds/json/client.cpp > build/.build.log 2>&1

build/obj/uds_json/linux/x86_64/release/src/uds/json/response.cpp.o: src/uds/json/response.cpp
	@echo compiling.release src/uds/json/response.cpp
	@mkdir -p build/obj/uds_json/linux/x86_64/release/src/uds/json
	@$(CXX) -c $(uds_json_CXXFLAGS) -o build/obj/uds_json/linux/x86_64/release/src/uds/json/response.cpp.o src/uds/json/response.cpp > build/.build.log 2>&1

build/obj/uds_json/linux/x86_64/release/src/uds/json/router.cpp.o: src/uds/json/router.cpp
	@echo compiling.release src/uds/json/router.cpp
	@mkdir -p build/obj/uds_json/linux/x86_64/release/src/uds/json
	@$(CXX) -c $(uds_json_CXXFLAGS) -o build/obj/uds_json/linux/x86_64/release/src/uds/json/router.cpp.o src/uds/json/router.cpp > build/.build.log 2>&1

build/obj/uds_json/linux/x86_64/release/src/uds/json/message.cpp.o: src/uds/json/message.cpp
	@echo compiling.release src/uds/json/message.cpp
	@mkdir -p build/obj/uds_json/linux/x86_64/release/src/uds/json
	@$(CXX) -c $(uds_json_CXXFLAGS) -o build/obj/uds_json/linux/x86_64/release/src/uds/json/message.cpp.o src/uds/json/message.cpp > build/.build.log 2>&1

build/obj/uds_json/linux/x86_64/release/src/uds/json/server.cpp.o: src/uds/json/server.cpp
	@echo compiling.release src/uds/json/server.cpp
	@mkdir -p build/obj/uds_json/linux/x86_64/release/src/uds/json
	@$(CXX) -c $(uds_json_CXXFLAGS) -o build/obj/uds_json/linux/x86_64/release/src/uds/json/server.cpp.o src/uds/json/server.cpp > build/.build.log 2>&1

uds_json_cli: bin/uds_json_cli
bin/uds_json_cli: lib/linux/release/libuds_json.a lib/linux/release/libuds_base.a build/obj/uds_json_cli/linux/x86_64/release/example/uds_json_cli/uds_json_cli.cpp.o
	@echo linking.release uds_json_cli
	@mkdir -p bin
	@$(LD) -o bin/uds_json_cli build/obj/uds_json_cli/linux/x86_64/release/example/uds_json_cli/uds_json_cli.cpp.o $(uds_json_cli_LDFLAGS) > build/.build.log 2>&1

build/obj/uds_json_cli/linux/x86_64/release/example/uds_json_cli/uds_json_cli.cpp.o: example/uds_json_cli/uds_json_cli.cpp
	@echo compiling.release example/uds_json_cli/uds_json_cli.cpp
	@mkdir -p build/obj/uds_json_cli/linux/x86_64/release/example/uds_json_cli
	@$(CXX) -c $(uds_json_cli_CXXFLAGS) -o build/obj/uds_json_cli/linux/x86_64/release/example/uds_json_cli/uds_json_cli.cpp.o example/uds_json_cli/uds_json_cli.cpp > build/.build.log 2>&1

simple_server: bin/simple_server
bin/simple_server: lib/linux/release/libuds_json.a lib/linux/release/libuds_base.a build/obj/simple_server/linux/x86_64/release/example/simple_json_server/server.cpp.o
	@echo linking.release simple_server
	@mkdir -p bin
	@$(LD) -o bin/simple_server build/obj/simple_server/linux/x86_64/release/example/simple_json_server/server.cpp.o $(simple_server_LDFLAGS) > build/.build.log 2>&1

build/obj/simple_server/linux/x86_64/release/example/simple_json_server/server.cpp.o: example/simple_json_server/server.cpp
	@echo compiling.release example/simple_json_server/server.cpp
	@mkdir -p build/obj/simple_server/linux/x86_64/release/example/simple_json_server
	@$(CXX) -c $(simple_server_CXXFLAGS) -o build/obj/simple_server/linux/x86_64/release/example/simple_json_server/server.cpp.o example/simple_json_server/server.cpp > build/.build.log 2>&1

echo_server: bin/echo_server
bin/echo_server: lib/linux/release/libuds_base.a build/obj/echo_server/linux/x86_64/release/example/echo_server/server.cpp.o
	@echo linking.release echo_server
	@mkdir -p bin
	@$(LD) -o bin/echo_server build/obj/echo_server/linux/x86_64/release/example/echo_server/server.cpp.o $(echo_server_LDFLAGS) > build/.build.log 2>&1

build/obj/echo_server/linux/x86_64/release/example/echo_server/server.cpp.o: example/echo_server/server.cpp
	@echo compiling.release example/echo_server/server.cpp
	@mkdir -p build/obj/echo_server/linux/x86_64/release/example/echo_server
	@$(CXX) -c $(echo_server_CXXFLAGS) -o build/obj/echo_server/linux/x86_64/release/example/echo_server/server.cpp.o example/echo_server/server.cpp > build/.build.log 2>&1

benchmark_client: bin/benchmark_client
bin/benchmark_client: lib/linux/release/libuds_base.a build/obj/benchmark_client/linux/x86_64/release/example/benchmark/client.cpp.o
	@echo linking.release benchmark_client
	@mkdir -p bin
	@$(LD) -o bin/benchmark_client build/obj/benchmark_client/linux/x86_64/release/example/benchmark/client.cpp.o $(benchmark_client_LDFLAGS) > build/.build.log 2>&1

build/obj/benchmark_client/linux/x86_64/release/example/benchmark/client.cpp.o: example/benchmark/client.cpp
	@echo compiling.release example/benchmark/client.cpp
	@mkdir -p build/obj/benchmark_client/linux/x86_64/release/example/benchmark
	@$(CXX) -c $(benchmark_client_CXXFLAGS) -o build/obj/benchmark_client/linux/x86_64/release/example/benchmark/client.cpp.o example/benchmark/client.cpp > build/.build.log 2>&1

clean:  clean_file_receiver clean_uds_base clean_file_sender clean_echo_client clean_simple_client clean_uds_base_cli clean_benchmark_server clean_uds_json clean_uds_json_cli clean_simple_server clean_echo_server clean_benchmark_client

clean_file_receiver:  clean_uds_base
	@rm -rf bin/file_receiver
	@rm -rf bin/file_receiver.sym
	@rm -rf build/obj/file_receiver/linux/x86_64/release/example/file_transfer/receiver.cpp.o

clean_uds_base: 
	@rm -rf lib/linux/release/libuds_base.a
	@rm -rf lib/linux/release/uds_base.sym
	@rm -rf build/obj/uds_base/linux/x86_64/release/src/uds/base/base_client.cpp.o
	@rm -rf build/obj/uds_base/linux/x86_64/release/src/uds/base/base_server.cpp.o
	@rm -rf build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/impl_base_client.cpp.o
	@rm -rf build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/uds_packet.cpp.o
	@rm -rf build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/impl_base_server.cpp.o
	@rm -rf build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/util/uds_util.cpp.o
	@rm -rf build/obj/uds_base/linux/x86_64/release/src/uds/base/impl/thread/static_thread_pool.cpp.o
	@rm -rf build/obj/uds_base/linux/x86_64/release/src/uds/base/error_code.cpp.o

clean_file_sender:  clean_uds_base
	@rm -rf bin/file_sender
	@rm -rf bin/file_sender.sym
	@rm -rf build/obj/file_sender/linux/x86_64/release/example/file_transfer/sender.cpp.o

clean_echo_client:  clean_uds_base
	@rm -rf bin/echo_client
	@rm -rf bin/echo_client.sym
	@rm -rf build/obj/echo_client/linux/x86_64/release/example/echo_server/client.cpp.o

clean_simple_client:  clean_uds_json clean_uds_base
	@rm -rf bin/simple_client
	@rm -rf bin/simple_client.sym
	@rm -rf build/obj/simple_client/linux/x86_64/release/example/simple_json_server/client.cpp.o

clean_uds_base_cli:  clean_uds_base
	@rm -rf bin/uds_base_cli
	@rm -rf bin/uds_base_cli.sym
	@rm -rf build/obj/uds_base_cli/linux/x86_64/release/example/uds_base_cli/uds_base_cli.cpp.o

clean_benchmark_server:  clean_uds_base
	@rm -rf bin/benchmark_server
	@rm -rf bin/benchmark_server.sym
	@rm -rf build/obj/benchmark_server/linux/x86_64/release/example/benchmark/server.cpp.o

clean_uds_json: 
	@rm -rf lib/linux/release/libuds_json.a
	@rm -rf lib/linux/release/uds_json.sym
	@rm -rf build/obj/uds_json/linux/x86_64/release/src/uds/json/request.cpp.o
	@rm -rf build/obj/uds_json/linux/x86_64/release/src/uds/json/client.cpp.o
	@rm -rf build/obj/uds_json/linux/x86_64/release/src/uds/json/response.cpp.o
	@rm -rf build/obj/uds_json/linux/x86_64/release/src/uds/json/router.cpp.o
	@rm -rf build/obj/uds_json/linux/x86_64/release/src/uds/json/message.cpp.o
	@rm -rf build/obj/uds_json/linux/x86_64/release/src/uds/json/server.cpp.o

clean_uds_json_cli:  clean_uds_json clean_uds_base
	@rm -rf bin/uds_json_cli
	@rm -rf bin/uds_json_cli.sym
	@rm -rf build/obj/uds_json_cli/linux/x86_64/release/example/uds_json_cli/uds_json_cli.cpp.o

clean_simple_server:  clean_uds_json clean_uds_base
	@rm -rf bin/simple_server
	@rm -rf bin/simple_server.sym
	@rm -rf build/obj/simple_server/linux/x86_64/release/example/simple_json_server/server.cpp.o

clean_echo_server:  clean_uds_base
	@rm -rf bin/echo_server
	@rm -rf bin/echo_server.sym
	@rm -rf build/obj/echo_server/linux/x86_64/release/example/echo_server/server.cpp.o

clean_benchmark_client:  clean_uds_base
	@rm -rf bin/benchmark_client
	@rm -rf bin/benchmark_client.sym
	@rm -rf build/obj/benchmark_client/linux/x86_64/release/example/benchmark/client.cpp.o

